# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='accounts.User'),
        ),
    ]
